import { Inter } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en ">
      <body className={outfit.className}>
        <Navbar></Navbar>
        {children}
        <Footer supportLinks={[]}></Footer>
      </body>
    </html>
  );
}
